const dummyData = [
  {
    id: 1,
    geoLocation: 'New York, NY',
    pickupDate: '2023-10-15',
    pickupTime: '10:00 AM',
    bookingOption: 'Standard',
    rideFormat: 'One-Way',
    preRideDate: '2023-10-14',
    bookingId: 'BK123456',
    bookingType: 'Personal',
    customerName: 'John Doe',
    pickupInformation: '123 Main St, New York, NY',
    airportInformation: 'JFK Airport, Terminal 4',
    stops: '1 stop',
    dropOffInformation: '456 Broadway, New York, NY',
    airportDropOffInformation: 'LGA Airport, Terminal B',
    noOfPassenger: 2,
    luggageDetails: '2 suitcases, 1 carry-on',
    accessibilityInformation: 'Wheelchair accessible',
    childSeat: 'Yes',
    beverage: 'No',
    serviceType: 'Luxury',
    vehicleCategory: 'SUV',
    estimatedMiles: 25,
    estimatedTime: '45 mins',
    flightType: 'Domestic',
    airline: 'Delta',
    flightNumber: 'DL123',
    apup: 'Yes',
    adop: 'No',
    flightStatus: 'On Time',
    apum: 'No',
    apcl: 'Yes',
    estimatedLandingTime: '2023-10-15 09:30 AM',
    actualLandingTime: '2023-10-15 09:35 AM',
    terminalGate: 'Terminal 4, Gate A5',
    notes: 'Customer prefers quiet ride',
    bookingDate: '2023-10-10',
    bookingTime: '03:00 PM',
    gratuity: '$10',
    preEstimatedFare: '$75',
    paymentType: 'Credit Card',
    cashBackUsed: '$5',
    cashBackEarned: '$2',
    milesPointUsed: '100 points',
    milesPointEarned: '50 points',
    discountPromo: '10% off',
    driverPercentage: '80%',
    driverPayment: '$60',
    rydeproPercentage: '20%',
    rydeproAmount: '$15',
    estimatedGrossFare: '$90',
    paymentStatus: 'Paid',
    areaIpCoordinates: '40.7128° N, 74.0060° W',
    preRideAdminStatus: 'Confirmed',
    preRideDriverStatus: 'Assigned',
    driverInformation: 'Jane Smith, License #12345',
    vehicleDetails: 'Black SUV, License Plate XYZ123',
    rideInProgressStatus: 'En Route',
    rideCompletionStatus: 'Completed',
    problemResolutionStatus: 'No Issues',
    emergencyStatus: 'None',
    riderFees: '$5',
    driverFees: '$10',
    preEstimatedMiles: 25,
    finalMiles: 26,
    preEstimatedTotalMiles: 25,
    additionalFees: '$0',
  },
  {
    id: 2,
    geoLocation: 'Los Angeles, CA',
    pickupDate: '2023-10-16',
    pickupTime: '02:00 PM',
    bookingOption: 'Premium',
    rideFormat: 'Round Trip',
    preRideDate: '2023-10-15',
    bookingId: 'BK654321',
    bookingType: 'Business',
    customerName: 'Jane Smith',
    pickupInformation: '789 Sunset Blvd, Los Angeles, CA',
    airportInformation: 'LAX Airport, Terminal 7',
    stops: 'No stops',
    dropOffInformation: '101 Hollywood Blvd, Los Angeles, CA',
    airportDropOffInformation: 'BUR Airport, Terminal A',
    noOfPassenger: 1,
    luggageDetails: '1 suitcase',
    accessibilityInformation: 'None',
    childSeat: 'No',
    beverage: 'Yes',
    serviceType: 'Standard',
    vehicleCategory: 'Sedan',
    estimatedMiles: 15,
    estimatedTime: '30 mins',
    flightType: 'International',
    airline: 'American Airlines',
    flightNumber: 'AA456',
    apup: 'No',
    adop: 'Yes',
    flightStatus: 'Delayed',
    apum: 'Yes',
    apcl: 'No',
    estimatedLandingTime: '2023-10-16 01:30 PM',
    actualLandingTime: '2023-10-16 01:45 PM',
    terminalGate: 'Terminal 7, Gate B2',
    notes: 'Customer requested water bottle',
    bookingDate: '2023-10-11',
    bookingTime: '10:00 AM',
    gratuity: '$15',
    preEstimatedFare: '$100',
    paymentType: 'PayPal',
    cashBackUsed: '$10',
    cashBackEarned: '$5',
    milesPointUsed: '200 points',
    milesPointEarned: '100 points',
    discountPromo: 'None',
    driverPercentage: '75%',
    driverPayment: '$75',
    rydeproPercentage: '25%',
    rydeproAmount: '$25',
    estimatedGrossFare: '$120',
    paymentStatus: 'Pending',
    areaIpCoordinates: '34.0522° N, 118.2437° W',
    preRideAdminStatus: 'Pending',
    preRideDriverStatus: 'Not Assigned',
    driverInformation: 'John Doe, License #67890',
    vehicleDetails: 'White Sedan, License Plate ABC789',
    rideInProgressStatus: 'Not Started',
    rideCompletionStatus: 'Not Completed',
    problemResolutionStatus: 'None',
    emergencyStatus: 'None',
    riderFees: '$10',
    driverFees: '$15',
    preEstimatedMiles: 15,
    finalMiles: 16,
    preEstimatedTotalMiles: 15,
    additionalFees: '$5',
  },
  // Add more dummy data objects as needed
];

export default dummyData;
